### ISSUE TITLE
Changing instance type to M5 instead of M4 fails

### ISSUE THREAD

**Issue by dayyehm** [aws-quickstart/quickstart-tableau-server#71]
The solution seems to be inconsistent when changing the instance type, can you provide a way of logging what is causing the stack update fails to change instance type to m5.2xlarge 
is there a specific hardware requirement /software requirement on linux to be used as a reference ?
with m5.large after receiving a failure signal in cloudformation, trying the script manually results in error of installation due to insufficient memory and hardware requirements

when updating the stack and change instance type to m5.2xlarge it fails to update like this : 
"Parameter InstanceType failed to satisfy constraint: must be a valid EC2 instance type."

**Comment by vsnyc** [comment]
The error message is coming straight from the template, can you confirm if the InstanceType was changed in both the master and the workload templates? You need to add `m5.2xlarge` in both the templates.

```
InstanceType:
    AllowedValues:
      - m4.4xlarge
      - m4.10xlarge
      - m5.4xlarge
      - m5.12xlarge
    ConstraintDescription: must be a valid EC2 instance type.
```
